### PR TITLE
Update spellId for Premonition, and make Call Felhunter default

### LINKED ISSUE #54: Premonition tracker doesn't work
Premonition isn't tracked when the enemy presses it.

### PR DESCRIPTION
**Pull request by ssdh233**
Fixed #54

### CODE REVIEW

**Comment by ssdh233** [comment]
@jordonwow Thanks for creating this amazing addon! I wanna help to keep it updated. Please check and feel free to leave comments when you have time :)

**Comment by ssdh233** [comment]
@jordonwow Please take a look when you have time :)

**Comment by jordonwow** [comment]
Thank you sorry it took so long to get this merged

**Comment by ssdh233** [comment]
Thanks for the merge!

Actually I accidentally put this commit(https://github.com/jordonwow/omnibar/pull/58/commits/160567090ce8d65e666f6e59419fc9e170f278e2) into this pull request. Anyway, glad to see that you like this feature!

**Pull request closed without merging**
